version: '3'
services:
  # app:
  #   build: .
  #   env_file:
  #     - .env
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/mydb
  mongo:
    image: mongo
    ports:
      - 27017:27017
    # depends_on:
    #   - app